# Numpy Tutorials
Numpy is a general-purpose array processing package.It provides a high performance multidimensional array object and tool for working with these arrays. It is the fundamental package for scientific computing with python.

# What is an array

An array is a data structure that stores values of same data type ([1,2,3,4] or ["a","b","c","d"]).In Python, this is the main difference array and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type.

In [1]:
#  use for multidimension array

In [2]:
import numpy as np

In [3]:
### One dimensional array
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
arr.shape

(5,)

In [6]:
type(arr)

numpy.ndarray

In [7]:
print(arr)

[1 2 3 4 5]


In [8]:
## Multidimensional array
list_1 = [1,2,3,4,5]
list_2 = [6,7,8,9,10]
list_3 = [11,12,13,14,15]
# converting these list into multidimension array
arr = np.array([list_1,list_2,list_3])

In [9]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
arr.shape  # 3 rows and 5 columns

(3, 5)

### Two dimension bracket 
It is always remember that in two dimensional bracket there are 2 opening bracket and 2 closing bracket.


In [11]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [12]:
arr.shape

(3, 5)

# Indexing

In [13]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [14]:
arr8 = np.array([1,2,3,4,5,6,7,8,9])

In [15]:
arr8[0]

1

In [16]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [17]:
arr[0:2,:] #  on left side you can print rows from start to finish using given numbers

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
arr[:,0:3] # on right side you can print column values

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [19]:
arr_9 = np.arange(0,100)

In [20]:
arr_9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [21]:
arr_9.reshape([20,5])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [22]:
arr_9 = np.arange(0,11, step =2)

In [23]:
arr_9

array([ 0,  2,  4,  6,  8, 10])

In [24]:
arr_9.reshape(3,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [25]:
arr_0 = np.arange(0,11)

In [26]:
arr_0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr_0[3:]=100

In [28]:
arr_0

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100, 100])

In [29]:
# Copy Function

In [30]:
arr_01 = arr_0.copy()

In [31]:
arr_0[3:]=500

In [32]:
print(arr_0)
print(arr_01)

[  0   1   2 500 500 500 500 500 500 500 500]
[  0   1   2 100 100 100 100 100 100 100 100]


In [33]:
# Some conditions very useful in exploratory data analaysis

In [34]:
arr_0

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500, 500])

In [35]:
arr_0*3 # perform all kind of math operation using this

array([   0,    3,    6, 1500, 1500, 1500, 1500, 1500, 1500, 1500, 1500])

In [36]:
arr_0[arr_0<500]

array([0, 1, 2])

In [37]:
## creating arrays and reshape
arr001 = np.arange(0,50).reshape(10,5)
arr002 = np.arange(0,50).reshape(10,5)

In [38]:
arr001*arr002

array([[   0,    1,    4,    9,   16],
       [  25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196],
       [ 225,  256,  289,  324,  361],
       [ 400,  441,  484,  529,  576],
       [ 625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156],
       [1225, 1296, 1369, 1444, 1521],
       [1600, 1681, 1764, 1849, 1936],
       [2025, 2116, 2209, 2304, 2401]])

In [39]:
np.ones(3) #  by default is float

array([1., 1., 1.])

In [40]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [41]:
np.ones(10,dtype=str)

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

In [42]:
### Random distribution
np.random.rand(3,3)

array([[0.84192186, 0.7780828 , 0.60148605],
       [0.1746156 , 0.76626361, 0.08310473],
       [0.32923475, 0.27582444, 0.64917213]])

In [43]:
np.random.rand(3,5)

array([[0.78793729, 0.04420629, 0.57022547, 0.38570572, 0.30365092],
       [0.5536567 , 0.48217815, 0.11636155, 0.78703853, 0.93344966],
       [0.0412698 , 0.83871258, 0.94508421, 0.73350252, 0.3363818 ]])

In [44]:
arr_ex = np.random.randn(4,4) # using standard normal distribution
arr_ex

array([[-1.27325044, -1.61407947, -0.05047469,  0.445737  ],
       [-1.18080864,  0.28511355, -0.60593437,  1.26619322],
       [-0.25469903, -0.09850698,  1.08729084,  0.63388972],
       [-0.3908045 , -0.36205026,  2.13423929, -0.95971442]])