In [1]:
import numpy as np

In [2]:
#simple lists
a = [1,2,3]
b = [4,5,6]
# print(a*b) # You cann't perform mathematical and statistical calculation simple array, it will give an error
display(a,b)

[1, 2, 3]

[4, 5, 6]

In [3]:
#numpy array
a_ = np.array([1,2,3])
b_ = np.array([4,5,6])
a_*b_

array([ 4, 10, 18])

In [4]:
a_+b_

array([5, 7, 9])

In [5]:
a_/b_

array([0.25, 0.4 , 0.5 ])

In [6]:
# two dimensional array
a1 = np.array([[1,2,3],[4,5,6]],dtype='float64')

In [7]:
a1.dtype

dtype('float64')

In [8]:
a1.shape

(2, 3)

In [9]:
a1.ndim

2

In [10]:
a1.nbytes

48

In [11]:
# three dimensional array
b1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [12]:
b1.ndim

3

In [13]:
b1.shape

(2, 2, 3)

### Accessing/Changing Specific Elements, Rows, Columns etc

In [14]:
# syntax of getting a specific element [row, column]
c = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
c.shape

(2, 6)

In [15]:
# get the no 10 in second row -- index starts from 0, 1-6 means 0 - 5
c[1,3] 

10

In [16]:
# print first row and all columns
c[0,]

array([1, 2, 3, 4, 5, 6])

In [17]:
# similarly print second row and columns step 2
c[1,::2] # third parameter is used for step

array([ 7,  9, 11])

In [18]:
c[0,1:6:2]

array([2, 4, 6])

In [19]:
# change the value of 12 to 15
c[1,5] = 15
print(c)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 15]]


In [20]:
b = np.array([[[1,2,34],[4,6,7]],[[10,12,16],[100,150,250]]])
b.ndim

3

In [21]:
b.shape # it shows 2 layers, 2 rows and 3 columns

(2, 2, 3)

In [22]:
# access first layer in no 34
b[0,0,2] # first layer, first row and third column

34

### Initializing different types of arrays

In [23]:
# all 0s matrix
np.zeros((3,3),dtype='int32')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
# all 1s matrix
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [25]:
# any other number
np.full((2,4,4),8, dtype='int32')

array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

In [26]:
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

In [27]:
#generating random numbers
np.random.rand(2,2)

array([[0.09323526, 0.45484148],
       [0.83534806, 0.5613173 ]])

In [28]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

### Be careful when copying array

In [29]:
d = np.array([1,2,3])
e = d
e[0] = 100
print(d)

[100   2   3]


In [30]:
# use this method
f = np.array([1,2,3])
g = f.copy()
g[0]= 100
print(g) # this will not change the value in original array

[100   2   3]


In [31]:
print(f)

[1 2 3]


### Mathematics

In [32]:
t = np.array([1,2,3,4,5,6])

In [33]:
t*2

array([ 2,  4,  6,  8, 10, 12])

In [34]:
t**2

array([ 1,  4,  9, 16, 25, 36], dtype=int32)

In [35]:
t+2

array([3, 4, 5, 6, 7, 8])

In [36]:
t += 2
t

array([3, 4, 5, 6, 7, 8])

In [37]:
t -= 3
t

array([0, 1, 2, 3, 4, 5])

In [38]:
u = np.array([7,8,9,10,11,12])
t*u

array([ 0,  8, 18, 30, 44, 60])

In [39]:
t+u

array([ 7,  9, 11, 13, 15, 17])

In [40]:
np.cos(t)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219])

### Linear Algebra

In [41]:
# IN linear algebra columns of the first matrix equal to the rows of second one

In [42]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),9)
print(b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[9 9]
 [9 9]
 [9 9]]


In [43]:
#Multiplying two matrixes
np.matmul(a,b)

array([[27., 27.],
       [27., 27.]])

### Statistics

In [44]:
stats  = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.max(stats)

6

In [46]:
np.min(stats)

1

In [47]:
np.sum(stats)

21

In [48]:
np.max(stats,axis=0)

array([4, 5, 6])

In [49]:
np.max(stats,axis=1)

array([3, 6])

## Reorganizing Arrays

In [50]:
before = np.array([[7,8,9],[10,11,12]])
print(before)
before.shape

[[ 7  8  9]
 [10 11 12]]


(2, 3)

In [51]:
after = before.reshape((3,2))
print(after)
print(after.shape)

[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [52]:
# Vertical stack of vectors - copy of vectors in vertical fashion
v1 = np.array([4,5,6,7])
v2 = np.array([8,9,10,11])
print("orginal = ",np.vstack([v1,v2]))

orginal =  [[ 4  5  6  7]
 [ 8  9 10 11]]


In [53]:
display([v1,v2,v1,v2,v2])

[array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([ 8,  9, 10, 11])]

In [54]:
# Horizontal Stack - copying in the horizonal fashion
np.hstack([v1,v2,v1,v2])

array([ 4,  5,  6,  7,  8,  9, 10, 11,  4,  5,  6,  7,  8,  9, 10, 11])

### Load data from different file using numpy

In [57]:
text = np.genfromtxt(r"C:\Users\Pc World Computers\OneDrive\Desktop\counting.txt",delimiter=',')
text.astype('int64')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  1,  0, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33],
      dtype=int64)

In [61]:
# Boolean Masking and Advance Indexing
text[text>10].astype('int64')

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33], dtype=int64)